menu:
    Blog: /
    Archive: /archives/
    Tag: /tags/
    About: /about/
    Contact: /contact/
    GitHub: https://github.com/luyao-wang
favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: luyaowang
cloudTie:

# Analytics
# google-analytics:
ga: UA-39886095-1

# Copyright Information
startyear: 2017
